# Configurable ore chances (percentages, they should add up to 140)
ore-chances:
  coal-ore: 35
  iron-ore: 25
  gold-ore: 15
  diamond-ore: 5
  emerald-ore: 5
  lapis-lazuli-ore: 5
  redstone-ore: 20
  copper-ore: 25
  quartz-ore: 5
